version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: miage-gpt-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - API_KEY=${API_KEY}
      - MONGODB_URI=mongodb://mongodb:27017/miage-gpt
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mongo-data:
